language: node_js
node_js:
  - "10.7"
before_script:
  - npm install
  - npm run build
script:
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  keep-history: true
  local-dir: .app
  committer-from-gh: true
  fqdn: vinski2.dandart.co.uk
  on:
    branch: master